<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-L7E7E43" name="mangoMain.SanitySuite.TestRun" tests="25" failures="2" timestamp="15 Jul 2019 13:14:28 GMT" time="545.843" errors="0">
  <testcase name="userExplicitLogin" time="9.883" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="defaultGroups" time="3.744" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="allUsersAddedToEveryOneGroup" time="7.120" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="projectCreation" time="21.137" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="documentConversion" time="26.691" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="fileUploadNewVersion" time="20.606" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="defaultLandingPageSetting" time="10.086" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="createPostFromCompose" time="25.861" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="createWikiFromCompose" time="26.788" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="createStaticPage" time="33.061" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="createDynamicPage" time="32.164" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="createRecurrenceTask" time="24.748" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="videoUploadNConversion" time="48.590" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="incomingEmailwithTeamID" time="36.526" classname="mangoMain.SanitySuite.TestRun">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at mangoMain.SanitySuite.TestRun.incomingEmailwithTeamID(TestRun.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- incomingEmailwithTeamID -->
  <testcase name="OutgoingEmailViaShare" time="17.221" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="incomingEmailReplyViaShare" time="7.055" classname="mangoMain.SanitySuite.TestRun">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at mangoMain.SanitySuite.TestRun.incomingEmailReplyViaShare(TestRun.java:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- incomingEmailReplyViaShare -->
  <testcase name="incomingEmailAsPrivateMessage" time="17.978" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="makeAFolderPublic" time="43.146" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="fileDeepSearch" time="9.930" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="verifyUsersInEveryone" time="7.434" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="ViewCounter" time="59.676" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="wikiTableOfContents" time="56.398" classname="mangoMain.SanitySuite.TestRun"/>
  <testcase name="userSingUp" classname="mangoMain.SanitySuite.TestRun">
    <skipped/>
  </testcase> <!-- userSingUp -->
  <testcase name="domainSignUp" classname="mangoMain.SanitySuite.TestRun">
    <skipped/>
  </testcase> <!-- domainSignUp -->
  <testcase name="logOutFromApplication" classname="mangoMain.SanitySuite.TestRun">
    <skipped/>
  </testcase> <!-- logOutFromApplication -->
</testsuite> <!-- mangoMain.SanitySuite.TestRun -->
